-- CapAventure v4 Schema
-- InnoDB utf8mb4 Biganos (33)
SET NAMES utf8mb4;
SET foreign_key_checks = 0;

CREATE TABLE IF NOT EXISTS `users` (`id` int NOT NULL AUTO_INCREMENT, `email` varchar(255) NOT NULL, `password` varchar(255) NOT NULL, `role` enum('admin','parent') NOT NULL DEFAULT 'parent', `prenom` varchar(100) NOT NULL, `nom` varchar(100) NOT NULL, `telephone` varchar(20) DEFAULT NULL, `actif` tinyint(1) NOT NULL DEFAULT 1, `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (`id`), UNIQUE KEY `uk_email` (`email`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `password_reset_tokens` (`id` int NOT NULL AUTO_INCREMENT, `token` varchar(255) NOT NULL, `expires_at` datetime NOT NULL, `used` tinyint(1) NOT NULL DEFAULT 0, `user_id` int DEFAULT NULL, `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (`id`), UNIQUE KEY `uk_token` (`token`), CONSTRAINT `fk_prt_user` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `children` (`id` int NOT NULL AUTO_INCREMENT, `user_id` int NOT NULL, `prenom` varchar(100) NOT NULL, `nom` varchar(100) NOT NULL, `date_naissance` date DEFAULT NULL, `allergie` text DEFAULT NULL, `medecin_nom` varchar(255) DEFAULT NULL, `medecin_telephone` varchar(20) DEFAULT NULL, `contact_urgence_nom` varchar(255) DEFAULT NULL, `contact_urgence_telephone` varchar(20) DEFAULT NULL, `contact_urgence_lien` varchar(100) DEFAULT NULL, `dossier_complete` tinyint(1) NOT NULL DEFAULT 0, `besoins_specifiques` tinyint(1) NOT NULL DEFAULT 0, `type_besoin` varchar(100) DEFAULT NULL, `niveau_autonomie` enum('total','partiel','accompagne') NOT NULL DEFAULT 'total', `centres_interet` text DEFAULT NULL, `activites_aimees` text DEFAULT NULL, `activites_a_eviter` text DEFAULT NULL, `declencheurs_crise` text DEFAULT NULL, `signes_avant_crise` text DEFAULT NULL, `hypersensibilites` text DEFAULT NULL, `hyposensibilites` text DEFAULT NULL, `methodes_apaisement` text DEFAULT NULL, `protocole_urgence` text DEFAULT NULL, `mode_communication` enum('verbal','pictogrammes','mixte','lsf','autre') NOT NULL DEFAULT 'verbal', `consignes_communication` text DEFAULT NULL, `traitement_medicamenteux` tinyint(1) NOT NULL DEFAULT 0, `details_traitement` text DEFAULT NULL, `niveau_natation` varchar(100) DEFAULT NULL, `infos_medicales` text DEFAULT NULL, `autorisation_sortie` tinyint(1) NOT NULL DEFAULT 1, `autorisation_photo` tinyint(1) NOT NULL DEFAULT 0, `suivi_professionnel` text DEFAULT NULL, `notes_animateur` text DEFAULT NULL, `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (`id`), KEY `idx_user` (`user_id`), CONSTRAINT `fk_child_user` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `slots` (`id` int NOT NULL AUTO_INCREMENT, `date` date NOT NULL, `periode` enum('matin','apres_midi','journee') NOT NULL DEFAULT 'journee', `heure_debut` time NOT NULL DEFAULT '09:00:00', `heure_fin` time NOT NULL DEFAULT '17:30:00', `places_max` tinyint NOT NULL DEFAULT 3 CHECK (`places_max` <= 3), `places_prises` tinyint NOT NULL DEFAULT 0, `type_accueil` enum('standard','adapte','mixte') NOT NULL DEFAULT 'mixte', `titre` varchar(255) DEFAULT NULL, `description` text DEFAULT NULL, `lieu` varchar(255) DEFAULT 'Biganos', `tarif` decimal(8,2) NOT NULL DEFAULT 25.00, `tarif_adapte` decimal(8,2) DEFAULT NULL, `statut` enum('ouvert','complet','annule','passe') NOT NULL DEFAULT 'ouvert', `actif` tinyint(1) NOT NULL DEFAULT 1, `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (`id`), INDEX `idx_date` (`date`), INDEX `idx_date_statut` (`date`, `statut`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `bookings` (`id` int NOT NULL AUTO_INCREMENT, `slot_id` int NOT NULL, `child_id` int NOT NULL, `user_id` int NOT NULL, `status` enum('pending','confirmed','cancelled','no_show') NOT NULL DEFAULT 'pending', `formule` enum('journee','demi_journee','semaine','mensuel') NOT NULL DEFAULT 'journee', `tarif_applique` decimal(8,2) NOT NULL DEFAULT 25.00, `paiement` enum('especes','virement','cesu') DEFAULT NULL, `paiement_statut` enum('en_attente','recu','rembourse') NOT NULL DEFAULT 'en_attente', `notes_parent` text DEFAULT NULL, `notes_animateur` text DEFAULT NULL, `compte_rendu` text DEFAULT NULL, `compte_rendu_at` datetime DEFAULT NULL, `present` tinyint(1) DEFAULT NULL, `heure_arrivee` time DEFAULT NULL, `heure_depart` time DEFAULT NULL, `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (`id`), UNIQUE KEY `uk_slot_child` (`slot_id`, `child_id`), INDEX `idx_slot` (`slot_id`), INDEX `idx_child` (`child_id`), INDEX `idx_user` (`user_id`), INDEX `idx_status` (`status`), CONSTRAINT `fk_booking_slot` FOREIGN KEY (`slot_id`) REFERENCES `slots`(`id`) ON DELETE RESTRICT, CONSTRAINT `fk_booking_child` FOREIGN KEY (`child_id`) REFERENCES `children`(`id`) ON DELETE CASCADE, CONSTRAINT `fk_booking_user` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `documents` (`id` int NOT NULL AUTO_INCREMENT, `user_id` int NOT NULL, `child_id` int DEFAULT NULL, `type` enum('ordonnance','pap','mdph','autorisation_sortie','autorisation_photo','autre') NOT NULL DEFAULT 'autre', `nom` varchar(255) NOT NULL, `filename` varchar(255) NOT NULL, `url` varchar(500) NOT NULL, `taille` int DEFAULT NULL, `valide` tinyint(1) DEFAULT NULL, `note_admin` text DEFAULT NULL, `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (`id`), KEY `idx_user` (`user_id`), KEY `idx_child` (`child_id`), CONSTRAINT `fk_doc_user` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE, CONSTRAINT `fk_doc_child` FOREIGN KEY (`child_id`) REFERENCES `children`(`id`) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `messages` (`id` int NOT NULL AUTO_INCREMENT, `sender_id` int NOT NULL, `receiver_id` int NOT NULL, `content` text NOT NULL, `lu` tinyint(1) NOT NULL DEFAULT 0, `archived` tinyint(1) NOT NULL DEFAULT 0, `deleted_at` datetime DEFAULT NULL, `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (`id`), KEY `idx_sender` (`sender_id`), KEY `idx_receiver` (`receiver_id`), CONSTRAINT `fk_msg_sender` FOREIGN KEY (`sender_id`) REFERENCES `users`(`id`) ON DELETE CASCADE, CONSTRAINT `fk_msg_receiver` FOREIGN KEY (`receiver_id`) REFERENCES `users`(`id`) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `planning_seances` (`id` int NOT NULL AUTO_INCREMENT, `slot_id` int DEFAULT NULL, `date` datetime NOT NULL, `titre` varchar(255) NOT NULL, `description` text DEFAULT NULL, `lieu` varchar(255) DEFAULT NULL, `notes_animateur` text DEFAULT NULL, `statut` enum('planifiee','confirmee','annulee') NOT NULL DEFAULT 'planifiee', `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (`id`), CONSTRAINT `fk_seance_slot` FOREIGN KEY (`slot_id`) REFERENCES `slots`(`id`) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `contact_requests` (`id` int NOT NULL AUTO_INCREMENT, `prenom` varchar(100) NOT NULL, `nom` varchar(100) DEFAULT NULL, `email` varchar(255) NOT NULL, `telephone` varchar(20) DEFAULT NULL, `service` enum('garde','repit','evenement','autre') DEFAULT NULL, `enfant_prenom` varchar(100) DEFAULT NULL, `enfant_age` varchar(20) DEFAULT NULL, `besoins_specifiques` tinyint(1) DEFAULT 0, `message` text DEFAULT NULL, `traite` tinyint(1) NOT NULL DEFAULT 0, `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (`id`), INDEX `idx_traite` (`traite`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

SET foreign_key_checks = 1;
SELECT 'Schema v4 OK' AS statut;
SHOW TABLES;
